住所を本郷から下井草に修正
Scout-Association-of-Japan/SAJ-DownloadCenter pull request #1
Opened 2020-03-11 15:21 UTC by caffisenna

フッター部の記載住所を修正しました

2020-03-11 23:17 UTC, 07JP27 commented
@caffisenna 
Hi! Thank you for your suggestion!
I reviewing now, Please wait a moment.

2020-03-12 03:39 UTC, 07JP27 requested changes

2020-03-12 03:39 UTC, 07JP27 commented on about.html
> +			Eメール:pr@scout.or.jp 電話:03-03-6913-6262<br />
@caffisenna 
電話番号の03が重複しているように見えます。
ご確認ください。

2020-03-12 04:07 UTC, caffisenna commented on about.html
> +			Eメール:pr@scout.or.jp 電話:03-03-6913-6262<br />
重複している03を修正しました。
ご確認お願い致します。

2020-03-12 08:33 UTC, 07JP27 commented on about.html
> +			Eメール:pr@scout.or.jp 電話:03-03-6913-6262<br />
確認しました。ありがとうございます。

2020-03-12 08:34 UTC, 07JP27 approved these changes
@caffisenna 
Congratulation!
You are first contributor to this Organization!

2020-03-12 08:34 UTC, merged