update R3 poster
Scout-Association-of-Japan/SAJ-DownloadCenter pull request #35
Opened 2022-04-05 07:12 UTC by caffisenna

2021年度普及資料A3ポスターの差し換え
- DLされるPDFは `saj-2021.pdf`
- ページ上のタイトルはR3

## 📝 関連issue / Related Issues

2022-04-05 07:23 UTC, 07JP27 requested changes

2022-04-05 07:23 UTC, 07JP27 commented on index.html
> -						<a href="content/poster/saj-poster-r2.html">
一覧ページはR2→R3への変更ですが、詳細ページはR3の新規作成に見えます。R2が不要（リンクが張られない）のであればR2の詳細ページを削除したほうが良いと思います。

2022-04-05 07:27 UTC, caffisenna commented on index.html
> -						<a href="content/poster/saj-poster-r2.html">
saj-poster-r2.html を削除しました。

2022-04-05 08:30 UTC, caffisenna commented
saj-poster-r3.html 内のタイトル
日本連盟ポスターR4 を
日本連盟ポスターR3 に修正しました。 🙇

2022-04-05 08:33 UTC, 07JP27 requested changes

2022-04-05 08:33 UTC, 07JP27 commented on content/poster/saj-poster-r3.html
> +					<a class="grey-text text-lighten-4 right">ボーイスカウト日本連盟事務局 社会連携・広報部</a>
クレジットがデグレってます（部署名無しが最新）

2022-04-05 08:40 UTC, caffisenna commented on content/poster/saj-poster-r3.html
> +					<a class="grey-text text-lighten-4 right">ボーイスカウト日本連盟事務局 社会連携・広報部</a>
部署削除しました

2022-04-06 00:08 UTC, 07JP27 approved these changes

2022-04-06 00:09 UTC, merged